version: '3.8'
services:
  djl-serving:
    image: iliasbro/mariposas:latest
    ports:
      - "8081:8080"
    environment:
      - MODEL_URL=file:/opt/djl/model.zip

  mariposas-app:
    image: iliasbro/mariposas:latest
    ports:
      - "8080:8080"
    environment:
      - DJL_INFERENCE_HOST=http://djl-serving:8080
    depends_on:
      - djl-serving
