version: '3.8'
services:
  djl-serving:
    image: iliasbro/mariposas:latest
    ports:
      - "8081:8080"
    volumes:
      - ./models:/opt/djl/model
    environment:
      - MODEL_URL=file:/opt/djl/model/model.zip

  mariposas-app:
    image: iliasbro/mariposas-app:latest
    ports:
      - "8082:8082"
    environment:
      - DJL_INFERENCE_HOST=http://djl-serving:8080
    depends_on:
      - djl-serving
